apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::848489028523:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::848489028523:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WIT0A1WQ8J6O
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-08-02T12:57:46Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1817'
  uid: 91d23d39-cb1d-43ed-819e-f33b2291afc3
